# Generated by Django 5.1.6 on 2025-03-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_seniorone_special_needs_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seniorone',
            name='aggregates',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, verbose_name='Aggregates'),
        ),
        migrations.AlterField(
            model_name='seniorone',
            name='cls',
            field=models.CharField(choices=[('Senior One', 'Senior One'), ('Senior Two', 'Senior Two'), ('Senior Three', 'Senior Three'), ('Senior Four', 'Senior Four')], max_length=20, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='seniorone',
            name='division',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='seniorone',
            name='dream_profession',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Engineer', 'Engineer'), ('Lawyer', 'Lawyer'), ('Pilot', 'Pilot'), ('Teacher', 'Teacher'), ('Nurse', 'Nurse'), ('Accountant', 'Accountant'), ('Journalist', 'Journalist'), ('Artist', 'Artist'), ('Musician', 'Musician'), ('Farmer', 'Farmer'), ('Other', 'Other')], max_length=20, verbose_name='Dream Profession'),
        ),
        migrations.AlterField(
            model_name='seniorone',
            name='elective',
            field=models.CharField(choices=[('ICT', 'ICT'), ('Music', 'Music'), ('French', 'French'), ('CRE', 'CRE'), ('Literature', 'Literature'), ('Agriculture', 'Agriculture'), ('Technical Drawing', 'Technical Drawing'), ('Food and Nutrition', 'Food and Nutrition'), ('Art and Design', 'Art and Design')], max_length=20, verbose_name='Elective Subject'),
        ),
        migrations.AlterField(
            model_name='seniorone',
            name='emergency_contact',
            field=models.CharField(max_length=10, verbose_name='Emergency Contact'),
        ),
        migrations.AlterField(
            model_name='seniorone',
            name='english',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=1, verbose_name='English'),
        ),
        migrations.AlterField(
            model_name='seniorone',
            name='home_address',
            field=models.CharField(max_length=100, verbose_name='Home Address'),
        ),
        migrations.AlterField(
            model_name='seniorone',
            name='index_no',
            field=models.CharField(max_length=10, verbose_name='Index Number'),
        ),
        migrations.AlterField(
            model_name='seniorone',
            name='mathematics',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=1, verbose_name='Mathematics'),
        ),
        migrations.AlterField(
            model_name='seniorone',
            name='religion',
            field=models.CharField(choices=[('Catholic', 'Catholic'), ('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Hindu', 'Hindu'), ('Adventist', 'Adventist'), ('Other', 'Other')], max_length=20, verbose_name='Religion'),
        ),
        migrations.AlterField(
            model_name='seniorone',
            name='science',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=1, verbose_name='Science'),
        ),
        migrations.AlterField(
            model_name='seniorone',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='seniorone',
            name='social_studies',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=1, verbose_name='Social Studies'),
        ),
    ]
