# Generated by Django 5.1.6 on 2025-03-09 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_alter_seniorone_aggregates_alter_seniorone_cls_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seniorone',
            name='special_needs_details',
        ),
    ]
